use_frameworks!

target 'Cactacea_Example' do
  pod 'Cactacea', :path => '../'

  target 'Cactacea_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
