use_frameworks!

target 'Cactacea_Example' do
  pod 'Cactacea', :path => '../'

  target 'Cactacea_Tests' do
    inherit! :search_paths

    pod 'RxSwift',    '~> 4.4.0'
    pod 'Alamofire', '~> 4.7.3'
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
