//
// Account.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Account: Codable {

    public var _id: Int64
    public var accountName: String
    public var displayName: String?
    public var profileImageUrl: String?
    public var friend: Bool
    public var friendRequestInProgress: Bool
    public var follow: Bool
    public var follower: Bool
    public var followCount: Int64?
    public var followerCount: Int64?
    public var friendCount: Int64?
    public var feedsCount: Int64?
    public var mute: Bool
    public var web: String?
    public var birthday: Int64?
    public var location: String?
    public var bio: String?
    public var joinedAt: Int64?
    public var next: Int64

    public init(_id: Int64, accountName: String, displayName: String?, profileImageUrl: String?, friend: Bool, friendRequestInProgress: Bool, follow: Bool, follower: Bool, followCount: Int64?, followerCount: Int64?, friendCount: Int64?, feedsCount: Int64?, mute: Bool, web: String?, birthday: Int64?, location: String?, bio: String?, joinedAt: Int64?, next: Int64) {
        self._id = _id
        self.accountName = accountName
        self.displayName = displayName
        self.profileImageUrl = profileImageUrl
        self.friend = friend
        self.friendRequestInProgress = friendRequestInProgress
        self.follow = follow
        self.follower = follower
        self.followCount = followCount
        self.followerCount = followerCount
        self.friendCount = friendCount
        self.feedsCount = feedsCount
        self.mute = mute
        self.web = web
        self.birthday = birthday
        self.location = location
        self.bio = bio
        self.joinedAt = joinedAt
        self.next = next
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case accountName
        case displayName
        case profileImageUrl
        case friend
        case friendRequestInProgress
        case follow
        case follower
        case followCount
        case followerCount
        case friendCount
        case feedsCount
        case mute
        case web
        case birthday
        case location
        case bio
        case joinedAt
        case next
    }


}

