//
// Feed.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Feed: Codable {

    public var _id: Int64
    public var message: String
    public var mediums: [Medium]?
    public var tags: [String]?
    public var account: Account?
    public var likeCount: Int64
    public var commentCount: Int64
    public var contentWarning: Bool
    public var contentDeleted: Bool
    public var postedAt: Int64
    public var next: Int64

    public init(_id: Int64, message: String, mediums: [Medium]?, tags: [String]?, account: Account?, likeCount: Int64, commentCount: Int64, contentWarning: Bool, contentDeleted: Bool, postedAt: Int64, next: Int64) {
        self._id = _id
        self.message = message
        self.mediums = mediums
        self.tags = tags
        self.account = account
        self.likeCount = likeCount
        self.commentCount = commentCount
        self.contentWarning = contentWarning
        self.contentDeleted = contentDeleted
        self.postedAt = postedAt
        self.next = next
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case message
        case mediums
        case tags
        case account
        case likeCount
        case commentCount
        case contentWarning
        case contentDeleted
        case postedAt
        case next
    }


}

