//
// FriendRequestId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FriendRequestId: Codable {

    public var value: Int64

    public init(value: Int64) {
        self.value = value
    }


}

