//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Message: Codable {

    public enum MessageType: String, Codable {
        case text = "text"
        case medium = "medium"
        case stamp = "stamp"
        case invitation = "invitation"
        case joined = "joined"
        case _left = "left"
    }
    public var _id: Int64
    public var messageType: MessageType
    public var message: String?
    public var medium: Medium?
    public var account: Account?
    public var unread: Bool
    public var accountCount: Int64
    public var readAccountCount: Int64
    public var contentWarning: Bool
    public var contentDeleted: Bool
    public var postedAt: Int64
    public var next: Int64?

    public init(_id: Int64, messageType: MessageType, message: String?, medium: Medium?, account: Account?, unread: Bool, accountCount: Int64, readAccountCount: Int64, contentWarning: Bool, contentDeleted: Bool, postedAt: Int64, next: Int64?) {
        self._id = _id
        self.messageType = messageType
        self.message = message
        self.medium = medium
        self.account = account
        self.unread = unread
        self.accountCount = accountCount
        self.readAccountCount = readAccountCount
        self.contentWarning = contentWarning
        self.contentDeleted = contentDeleted
        self.postedAt = postedAt
        self.next = next
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case messageType
        case message
        case medium
        case account
        case unread
        case accountCount
        case readAccountCount
        case contentWarning
        case contentDeleted
        case postedAt
        case next
    }


}

