//
// PutSessionProfileBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PutSessionProfileBody: Codable {

    /** Display name. */
    public var displayName: String
    /** Profile URL. */
    public var web: String
    /** Account birthday. */
    public var birthday: Int64
    /** Account address. */
    public var location: String
    /** Account bio. */
    public var bio: String

    public init(displayName: String, web: String, birthday: Int64, location: String, bio: String) {
        self.displayName = displayName
        self.web = web
        self.birthday = birthday
        self.location = location
        self.bio = bio
    }

    public enum CodingKeys: String, CodingKey { 
        case displayName = "display_name"
        case web
        case birthday
        case location
        case bio
    }


}

