//
// AccountStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AccountStatus: Codable {

    public enum Status: String, Codable { 
        case active = "active"
        case inactive = "inactive"
    }
    public var id: Int64
    public var status: Status


    
    public init(id: Int64, status: Status) {
        self.id = id
        self.status = status
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(status, forKey: "status")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(Int64.self, forKey: "id")
        status = try container.decode(Status.self, forKey: "status")
    }
}

