//
// CactaceaErrors.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CactaceaErrors: Codable {

    public var errors: [CactaceaError]


    
    public init(errors: [CactaceaError]) {
        self.errors = errors
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(errors, forKey: "errors")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        errors = try container.decode([CactaceaError].self, forKey: "errors")
    }
}

