//
// Comment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Comment: Codable {

    public var id: Int64
    public var replyId: Int64?
    public var feedId: Int64
    public var message: String
    public var user: User
    public var likeCount: Int64
    public var warning: Bool
    public var rejected: Bool
    public var postedAt: Int64
    public var next: Int64


    
    public init(id: Int64, replyId: Int64?, feedId: Int64, message: String, user: User, likeCount: Int64, warning: Bool, rejected: Bool, postedAt: Int64, next: Int64) {
        self.id = id
        self.replyId = replyId
        self.feedId = feedId
        self.message = message
        self.user = user
        self.likeCount = likeCount
        self.warning = warning
        self.rejected = rejected
        self.postedAt = postedAt
        self.next = next
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encodeIfPresent(replyId, forKey: "replyId")
        try container.encode(feedId, forKey: "feedId")
        try container.encode(message, forKey: "message")
        try container.encode(user, forKey: "user")
        try container.encode(likeCount, forKey: "likeCount")
        try container.encode(warning, forKey: "warning")
        try container.encode(rejected, forKey: "rejected")
        try container.encode(postedAt, forKey: "postedAt")
        try container.encode(next, forKey: "next")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(Int64.self, forKey: "id")
        replyId = try container.decodeIfPresent(Int64.self, forKey: "replyId")
        feedId = try container.decode(Int64.self, forKey: "feedId")
        message = try container.decode(String.self, forKey: "message")
        user = try container.decode(User.self, forKey: "user")
        likeCount = try container.decode(Int64.self, forKey: "likeCount")
        warning = try container.decode(Bool.self, forKey: "warning")
        rejected = try container.decode(Bool.self, forKey: "rejected")
        postedAt = try container.decode(Int64.self, forKey: "postedAt")
        next = try container.decode(Int64.self, forKey: "next")
    }
}

