//
// GetFeedsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class GetFeedsBody: Codable {

    public enum PrivacyType: String, Codable { 
        case everyone = "everyone"
        case followers = "followers"
        case friends = "friends"
        case _self = "self"
    }
    /** Feed privacy type. By default the value is everyone. */
    public var privacyType: PrivacyType?


    
    public init(privacyType: PrivacyType?) {
        self.privacyType = privacyType
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(privacyType, forKey: "privacy_type")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        privacyType = try container.decodeIfPresent(PrivacyType.self, forKey: "privacy_type")
    }
}

