//
// Invitation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Invitation: Codable {

    public var id: Int64
    public var channel: Channel
    public var user: User
    public var invitedAt: Int64
    public var next: Int64


    
    public init(id: Int64, channel: Channel, user: User, invitedAt: Int64, next: Int64) {
        self.id = id
        self.channel = channel
        self.user = user
        self.invitedAt = invitedAt
        self.next = next
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encode(channel, forKey: "channel")
        try container.encode(user, forKey: "user")
        try container.encode(invitedAt, forKey: "invitedAt")
        try container.encode(next, forKey: "next")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(Int64.self, forKey: "id")
        channel = try container.decode(Channel.self, forKey: "channel")
        user = try container.decode(User.self, forKey: "user")
        invitedAt = try container.decode(Int64.self, forKey: "invitedAt")
        next = try container.decode(Int64.self, forKey: "next")
    }
}

