//
// PostSocialLinkBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PostSocialLinkBody: Codable {

    /** token. */
    public var token: String
    /** expiresIn. */
    public var expiresIn: Int64
    /** secret. */
    public var secret: String


    
    public init(token: String, expiresIn: Int64, secret: String) {
        self.token = token
        self.expiresIn = expiresIn
        self.secret = secret
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(token, forKey: "token")
        try container.encode(expiresIn, forKey: "expiresIn")
        try container.encode(secret, forKey: "secret")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        token = try container.decode(String.self, forKey: "token")
        expiresIn = try container.decode(Int64.self, forKey: "expiresIn")
        secret = try container.decode(String.self, forKey: "secret")
    }
}

