//
// PostInvitationsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PostInvitationsBody: Codable {

    /** User Identifies. */
    public var userIds: [Int64]?


    
    public init(userIds: [Int64]?) {
        self.userIds = userIds
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(userIds, forKey: "userIds")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        userIds = try container.decodeIfPresent([Int64].self, forKey: "userIds")
    }
}

