//
// PostMessageBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PostMessageBody: Codable {

    /** Group identifier. */
    public var id: Int64
    /** A message will be posted. */
    public var message: String?
    /** A medium will be posted. */
    public var mediumId: Int64?


    
    public init(id: Int64, message: String?, mediumId: Int64?) {
        self.id = id
        self.message = message
        self.mediumId = mediumId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(id, forKey: "id")
        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(mediumId, forKey: "mediumId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decode(Int64.self, forKey: "id")
        message = try container.decodeIfPresent(String.self, forKey: "message")
        mediumId = try container.decodeIfPresent(Int64.self, forKey: "mediumId")
    }
}

