//
// PostSignInBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PostSignInBody: Codable {

    public enum AuthType: String, Codable { 
        case username = "username"
        case email = "email"
    }
    /** Auth type. */
    public var authType: AuthType
    /** User name. */
    public var identifier: String
    /** User password. */
    public var password: String


    
    public init(authType: AuthType, identifier: String, password: String) {
        self.authType = authType
        self.identifier = identifier
        self.password = password
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(authType, forKey: "authType")
        try container.encode(identifier, forKey: "identifier")
        try container.encode(password, forKey: "password")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        authType = try container.decode(AuthType.self, forKey: "authType")
        identifier = try container.decode(String.self, forKey: "identifier")
        password = try container.decode(String.self, forKey: "password")
    }
}

