//
// PutAccountDisplayNameBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PutAccountDisplayNameBody: Codable {

    /** Display name that each account shown. */
    public var displayName: String?


    
    public init(displayName: String?) {
        self.displayName = displayName
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(displayName, forKey: "display_name")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        displayName = try container.decodeIfPresent(String.self, forKey: "display_name")
    }
}

