//
// PutSessionPasswordBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PutSessionPasswordBody: Codable {

    /** Account old password. */
    public var oldPassword: String
    /** Account new password. */
    public var newPassword: String


    
    public init(oldPassword: String, newPassword: String) {
        self.oldPassword = oldPassword
        self.newPassword = newPassword
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(oldPassword, forKey: "old_password")
        try container.encode(newPassword, forKey: "new_password")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        oldPassword = try container.decode(String.self, forKey: "old_password")
        newPassword = try container.decode(String.self, forKey: "new_password")
    }
}

