//
// AccountsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class AccountsAPI {
    /**
     Confirm account name exist
     
     - parameter accountName: (path) Account name. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func existAccountName(accountName: String, completion: @escaping ((_ data: AccountNameNotExists?,_ error: Error?) -> Void)) {
        existAccountNameWithRequestBuilder(accountName: accountName).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Confirm account name exist
     
     - parameter accountName: (path) Account name. 
     - returns: Observable<AccountNameNotExists>
     */
    open class func existAccountName(accountName: String) -> Observable<AccountNameNotExists> {
        return Observable.create { observer -> Disposable in
            existAccountName(accountName: accountName) { data, error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Confirm account name exist
     - GET /account/{account_name}
     - API Key:
       - type: apiKey X-API-KEY 
       - name: api_key
     - OAuth:
       - type: oauth2
       - name: cactacea_auth
     - examples: [{contentType=application/json, example={
  "accountName" : "accountName",
  "exists" : true
}}]
     
     - parameter accountName: (path) Account name. 

     - returns: RequestBuilder<AccountNameNotExists> 
     */
    open class func existAccountNameWithRequestBuilder(accountName: String) -> RequestBuilder<AccountNameNotExists> {
        var path = "/account/{account_name}"
        path = path.replacingOccurrences(of: "{account_name}", with: "\(accountName)", options: .literal, range: nil)
        let URLString = CactaceaAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<AccountNameNotExists>.Type = CactaceaAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get information about a account
     
     - parameter id: (path) Account identifier. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func findAccount(id: Int64, completion: @escaping ((_ data: Account?,_ error: Error?) -> Void)) {
        findAccountWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Get information about a account
     
     - parameter id: (path) Account identifier. 
     - returns: Observable<Account>
     */
    open class func findAccount(id: Int64) -> Observable<Account> {
        return Observable.create { observer -> Disposable in
            findAccount(id: id) { data, error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Get information about a account
     - GET /accounts/{id}
     - API Key:
       - type: apiKey X-API-KEY 
       - name: api_key
     - OAuth:
       - type: oauth2
       - name: cactacea_auth
     - examples: [{contentType=application/json, example={
  "birthday" : 5.63737665663332876420099637471139430999755859375,
  "next" : 7,
  "follower" : true,
  "followCount" : 6.02745618307040320615897144307382404804229736328125,
  "friendCount" : 5.962133916683182377482808078639209270477294921875,
  "accountName" : "accountName",
  "displayName" : "displayName",
  "joinedAt" : 2.3021358869347654518833223846741020679473876953125,
  "bio" : "bio",
  "mute" : true,
  "follow" : true,
  "friendRequestInProgress" : true,
  "web" : "web",
  "friend" : true,
  "location" : "location",
  "id" : 0.80082819046101150206595775671303272247314453125,
  "profileImageUrl" : "profileImageUrl",
  "followerCount" : 1.46581298050294517310021547018550336360931396484375
}}]
     
     - parameter id: (path) Account identifier. 

     - returns: RequestBuilder<Account> 
     */
    open class func findAccountWithRequestBuilder(id: Int64) -> RequestBuilder<Account> {
        var path = "/accounts/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = CactaceaAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Account>.Type = CactaceaAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get account on
     
     - parameter id: (path) Account identifier. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func findAccountStatus(id: Int64, completion: @escaping ((_ data: AccountStatus?,_ error: Error?) -> Void)) {
        findAccountStatusWithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Get account on
     
     - parameter id: (path) Account identifier. 
     - returns: Observable<AccountStatus>
     */
    open class func findAccountStatus(id: Int64) -> Observable<AccountStatus> {
        return Observable.create { observer -> Disposable in
            findAccountStatus(id: id) { data, error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Get account on
     - GET /accounts/{id}/status
     - API Key:
       - type: apiKey X-API-KEY 
       - name: api_key
     - OAuth:
       - type: oauth2
       - name: cactacea_auth
     - examples: [{contentType=application/json, example={
  "id" : 0.80082819046101150206595775671303272247314453125,
  "status" : "active"
}}]
     
     - parameter id: (path) Account identifier. 

     - returns: RequestBuilder<AccountStatus> 
     */
    open class func findAccountStatusWithRequestBuilder(id: Int64) -> RequestBuilder<AccountStatus> {
        var path = "/accounts/{id}/status"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = CactaceaAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<AccountStatus>.Type = CactaceaAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Search accounts
     
     - parameter displayName: (query) Filters accounts whose display name start of. (optional)
     - parameter since: (query) Filters accounts which started on since or later. (optional)
     - parameter offset: (query) The offset of accounts. By default the value is 0. (optional)
     - parameter count: (query) Maximum number of accounts returned on one result page. By default the value is 20 accounts. The page size can never be larger than 50. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func findAccounts(displayName: String? = nil, since: Int64? = nil, offset: Int64? = nil, count: Int64? = nil, completion: @escaping ((_ data: [Account]?,_ error: Error?) -> Void)) {
        findAccountsWithRequestBuilder(displayName: displayName, since: since, offset: offset, count: count).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     Search accounts
     
     - parameter displayName: (query) Filters accounts whose display name start of. (optional)
     - parameter since: (query) Filters accounts which started on since or later. (optional)
     - parameter offset: (query) The offset of accounts. By default the value is 0. (optional)
     - parameter count: (query) Maximum number of accounts returned on one result page. By default the value is 20 accounts. The page size can never be larger than 50. (optional)
     - returns: Observable<[Account]>
     */
    open class func findAccounts(displayName: String? = nil, since: Int64? = nil, offset: Int64? = nil, count: Int64? = nil) -> Observable<[Account]> {
        return Observable.create { observer -> Disposable in
            findAccounts(displayName: displayName, since: since, offset: offset, count: count) { data, error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Search accounts
     - GET /accounts
     - API Key:
       - type: apiKey X-API-KEY 
       - name: api_key
     - OAuth:
       - type: oauth2
       - name: cactacea_auth
     - examples: [{contentType=application/json, example=[ {
  "birthday" : 5.63737665663332876420099637471139430999755859375,
  "next" : 7,
  "follower" : true,
  "followCount" : 6.02745618307040320615897144307382404804229736328125,
  "friendCount" : 5.962133916683182377482808078639209270477294921875,
  "accountName" : "accountName",
  "displayName" : "displayName",
  "joinedAt" : 2.3021358869347654518833223846741020679473876953125,
  "bio" : "bio",
  "mute" : true,
  "follow" : true,
  "friendRequestInProgress" : true,
  "web" : "web",
  "friend" : true,
  "location" : "location",
  "id" : 0.80082819046101150206595775671303272247314453125,
  "profileImageUrl" : "profileImageUrl",
  "followerCount" : 1.46581298050294517310021547018550336360931396484375
}, {
  "birthday" : 5.63737665663332876420099637471139430999755859375,
  "next" : 7,
  "follower" : true,
  "followCount" : 6.02745618307040320615897144307382404804229736328125,
  "friendCount" : 5.962133916683182377482808078639209270477294921875,
  "accountName" : "accountName",
  "displayName" : "displayName",
  "joinedAt" : 2.3021358869347654518833223846741020679473876953125,
  "bio" : "bio",
  "mute" : true,
  "follow" : true,
  "friendRequestInProgress" : true,
  "web" : "web",
  "friend" : true,
  "location" : "location",
  "id" : 0.80082819046101150206595775671303272247314453125,
  "profileImageUrl" : "profileImageUrl",
  "followerCount" : 1.46581298050294517310021547018550336360931396484375
} ]}]
     
     - parameter displayName: (query) Filters accounts whose display name start of. (optional)
     - parameter since: (query) Filters accounts which started on since or later. (optional)
     - parameter offset: (query) The offset of accounts. By default the value is 0. (optional)
     - parameter count: (query) Maximum number of accounts returned on one result page. By default the value is 20 accounts. The page size can never be larger than 50. (optional)

     - returns: RequestBuilder<[Account]> 
     */
    open class func findAccountsWithRequestBuilder(displayName: String? = nil, since: Int64? = nil, offset: Int64? = nil, count: Int64? = nil) -> RequestBuilder<[Account]> {
        let path = "/accounts"
        let URLString = CactaceaAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "display_name": displayName, 
            "since": since, 
            "offset": offset, 
            "count": count
        ])
        

        let requestBuilder: RequestBuilder<[Account]>.Type = CactaceaAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Report a account
     
     - parameter id: (path) Account Identifier. 
     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func reportAccount(id: Int64, body: PostAccountReportBody, completion: @escaping ((_ error: Error?) -> Void)) {
        reportAccountWithRequestBuilder(id: id, body: body).execute { (response, error) -> Void in
            completion(error);
        }
    }

    /**
     Report a account
     
     - parameter id: (path) Account Identifier. 
     - parameter body: (body)  
     - returns: Observable<Void>
     */
    open class func reportAccount(id: Int64, body: PostAccountReportBody) -> Observable<Void> {
        return Observable.create { observer -> Disposable in
            reportAccount(id: id, body: body) { error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(()))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Report a account
     - POST /accounts/{id}/reports
     - API Key:
       - type: apiKey X-API-KEY 
       - name: api_key
     - OAuth:
       - type: oauth2
       - name: cactacea_auth
     
     - parameter id: (path) Account Identifier. 
     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func reportAccountWithRequestBuilder(id: Int64, body: PostAccountReportBody) -> RequestBuilder<Void> {
        var path = "/accounts/{id}/reports"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = CactaceaAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = CactaceaAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Change display name to session account
     
     - parameter id: (path) Account Identifier. 
     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateDisplayName(id: Int64, body: PutAccountDisplayNameBody, completion: @escaping ((_ error: Error?) -> Void)) {
        updateDisplayNameWithRequestBuilder(id: id, body: body).execute { (response, error) -> Void in
            completion(error);
        }
    }

    /**
     Change display name to session account
     
     - parameter id: (path) Account Identifier. 
     - parameter body: (body)  
     - returns: Observable<Void>
     */
    open class func updateDisplayName(id: Int64, body: PutAccountDisplayNameBody) -> Observable<Void> {
        return Observable.create { observer -> Disposable in
            updateDisplayName(id: id, body: body) { error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(()))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Change display name to session account
     - PUT /accounts/{id}/display_name
     - API Key:
       - type: apiKey X-API-KEY 
       - name: api_key
     - OAuth:
       - type: oauth2
       - name: cactacea_auth
     
     - parameter id: (path) Account Identifier. 
     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func updateDisplayNameWithRequestBuilder(id: Int64, body: PutAccountDisplayNameBody) -> RequestBuilder<Void> {
        var path = "/accounts/{id}/display_name"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = CactaceaAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = CactaceaAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
