//
// PasswordAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class PasswordAPI {
    /**
     Recover password
     
     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func recover(body: PostRecoverBody, completion: @escaping ((_ error: Error?) -> Void)) {
        recoverWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(error);
        }
    }

    /**
     Recover password
     
     - parameter body: (body)  
     - returns: Observable<Void>
     */
    open class func recover(body: PostRecoverBody) -> Observable<Void> {
        return Observable.create { observer -> Disposable in
            recover(body: body) { error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(()))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Recover password
     - POST /password/recover
     
     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func recoverWithRequestBuilder(body: PostRecoverBody) -> RequestBuilder<Void> {
        let path = "/password/recover"
        let URLString = CactaceaAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = CactaceaAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Reset Password
     
     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func reset(body: PostResetBody, completion: @escaping ((_ error: Error?) -> Void)) {
        resetWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(error);
        }
    }

    /**
     Reset Password
     
     - parameter body: (body)  
     - returns: Observable<Void>
     */
    open class func reset(body: PostResetBody) -> Observable<Void> {
        return Observable.create { observer -> Disposable in
            reset(body: body) { error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(()))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     Reset Password
     - POST /password/reset
     
     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func resetWithRequestBuilder(body: PostResetBody) -> RequestBuilder<Void> {
        let path = "/password/reset"
        let URLString = CactaceaAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = CactaceaAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
